name: Android CI

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build APK
      run: ./gradlew assemble
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: Release APK
        # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: '/home/runner/work/Neety/Neety/app/build/outputs/apk/release/app-release-unsigned.apk'
        retention-days: 5
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: '/home/runner/work/Neety/Neety/app/build/outputs/apk/release/app-release-unsigned.apk'
